### ISSUE TITLE
igv-webapp fails to start (npm reports that the start script is missing)

### ISSUE THREAD

**Issue by pwaltman** [dceoy/docker-bio#2]
see bash history below:

waltman@waltman-Q504UAK: docker pull dceoy/igv-webapp
Using default tag: latest
latest: Pulling from dceoy/igv-webapp
Digest: sha256:22e98a6f2c5d7b6f6946083c805560161a9d3869be05778fb50c63272c55367c
Status: Image is up to date for dceoy/igv-webapp:latest
docker.io/dceoy/igv-webapp:latest

waltman@waltman-Q504UAK:~ docker run --rm -it --user $(id -u):$(id -g) -p 8080:8080 -v /home/waltman:/home/waltman dceoy/igv-webapp /bin/bash
**npm ERR! Missing script: "start"**
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

**Comment by dceoy** [comment]
I updated the Dockerfile at https://github.com/dceoy/docker-bio/commit/f9c085acc65c0a22d42c97dbf95d37f02e70ab32.

- Pull the image and run a web server at port 8080.

  ```sh
  $ docker image pull dceoy/igv-webapp:latest
  $ docker container run --rm -p 80:80 dceoy/igv-webapp:latest  # -> http://127.0.0.1/
  ```
