### ISSUE TITLE
Need some help to start

### ISSUE THREAD

**Issue by Mieszkol** [dceoy/docker-bio#3]
Hi Daichi,

I'm new to docker and I need some help with starting to use your dockerfile. My goal is to use RSEM and BOWTIE2, specifically `rsem-prepare-reference `and `rsem-calculate-expression` commands. I pulled the latest dceoy/rsem image and tried to run it:
```
(base) Mieszkos-Mac-mini:~ mieszko$ docker container run -it dceoy/rsem
Invalid number of arguments!
NAME
    rsem-calculate-expression - Estimate gene and isoform expression from
    RNA-Seq data.

SYNOPSIS
     rsem-calculate-expression [options] upstream_read_file(s) reference_name sample_name 
     rsem-calculate-expression [options] --paired-end upstream_read_file(s) downstream_read_file(s) reference_name sample_name 
     rsem-calculate-expression [options] --alignments [--paired-end] input reference_name sample_name

```
As you can see I automatically got the output of `rsem-calculate-expression --help`. Is there a way to run your container in interactive mode and use commands of packages included in it (STAR, Bowtie2, RSEM)?

Thank you for help!

Best,
Mieszko

**Comment by dceoy** [comment]
You can use an interactive shell with `-it --entrypoint=bash` as follows:

```sh
$ docker container run --rm -it --entrypoint=bash -v ${PWD}:/wd -w /wd dceoy/rsem:latest
```
