### ISSUE TITLE
The `dceoy/fastp` image is using a very old version of `fastp`

### ISSUE THREAD

**Issue by naity2** [dceoy/docker-bio#6]
Hi @dceoy,

First, thank you so much for providing these wonderful docker images!

It looks like the `dceoy/fastp` image is using a very old version of `fastp` as shown below:

```
root@2dfe47d911df:/# fastp
fastp: an ultra-fast all-in-one FASTQ preprocessor
version 0.12.4
usage: fastp --in1=string [options] ... 
```
Would you please take a look and help update the tool if you have a moment?

Thanks very much!

**Comment by dceoy** [comment]
I replaced Bioconda's `fastp` (the old version) with the latest prebuilt binary at a1abd77f592436a4cf51e3aacd790880b7ddd7ce.

**Comment by naity2** [comment]
Awesome, thank you!
